/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.rs"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: "hsl(var(--card))",
        "card-foreground": "hsl(var(--card-foreground))",
        popover: "hsl(var(--popover))",
        "popover-foreground": "hsl(var(--popover-foreground))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        secondary: "hsl(var(--secondary))",
        "secondary-foreground": "hsl(var(--secondary-foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        accent: "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
        destructive: "hsl(var(--destructive))",
        "destructive-foreground": "hsl(var(--destructive-foreground))",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        sidebar: "hsl(var(--sidebar))",
        "sidebar-foreground": "hsl(var(--sidebar-foreground))",
        "sidebar-primary": "hsl(var(--sidebar-primary))",
        "sidebar-primary-foreground": "hsl(var(--sidebar-primary-foreground))",
        "sidebar-accent": "hsl(var(--sidebar-accent))",
        "sidebar-accent-foreground": "hsl(var(--sidebar-accent-foreground))",
        "sidebar-border": "hsl(var(--sidebar-border))",
        "sidebar-ring": "hsl(var(--sidebar-ring))",
        "message-own": "hsl(var(--message-own))",
        "message-own-foreground": "hsl(var(--message-own-foreground))",
        "message-other": "hsl(var(--message-other))",
        "message-other-foreground": "hsl(var(--message-other-foreground))",
        online: "hsl(var(--online))",
        read: "hsl(var(--read))",
        warning: "hsl(var(--warning))",
        "warning-foreground": "hsl(var(--warning-foreground))",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "fade-in": { from: { opacity: "0" }, to: { opacity: "1" } },
        "dialog-in": {
          from: { opacity: "0", transform: "scale(.96) translateY(4px)" },
          to: { opacity: "1", transform: "none" },
        },
        "dropdown-in": {
          from: { opacity: "0", transform: "scale(.96) translateY(-4px)" },
          to: { opacity: "1", transform: "none" },
        },
        "sheet-right-in": {
          from: { transform: "translateX(100%)" },
          to: { transform: "translateX(0)" },
        },
        "sheet-bottom-in": {
          from: { transform: "translateY(100%)" },
          to: { transform: "translateY(0)" },
        },
        "toast-in": {
          from: { opacity: "0", transform: "translateX(16px)" },
          to: { opacity: "1", transform: "none" },
        },
        "message-in": {
          from: { opacity: "0", transform: "translateY(6px)" },
          to: { opacity: "1", transform: "none" },
        },
        "screen-in": {
          from: { opacity: "0", transform: "translateX(12px)" },
          to: { opacity: "1", transform: "none" },
        },
      },
      animation: {
        "fade-in": "fade-in .15s ease-out",
        "overlay-in": "fade-in .2s ease-out",
        "dialog-in": "dialog-in .18s cubic-bezier(.16,1,.3,1)",
        "dropdown-in": "dropdown-in .14s ease-out",
        "sheet-right-in": "sheet-right-in .25s cubic-bezier(.16,1,.3,1)",
        "sheet-bottom-in": "sheet-bottom-in .28s cubic-bezier(.16,1,.3,1)",
        "toast-in": "toast-in .2s ease-out",
        "message-in": "message-in .18s ease-out",
        "screen-in": "screen-in .2s cubic-bezier(.16,1,.3,1)",
      },
    },
  },
};
