//! Mock data for the UI prototype.
//!
//! All data is static — no real network or crypto calls.

use std::cell::RefCell;

// ── Types (shared) ──────────────────────────────────────────────────────────

#[derive(Clone, Debug)]
pub struct User {
    pub id: String,
    pub username: String,
    pub display_name: String,
    pub avatar_url: Option<String>,
    pub bio: Option<String>,
    pub role: String,
    pub created_at: f64,
}

#[derive(Clone, Debug)]
pub struct Device {
    pub id: String,
    pub name: String,
    pub device_type: String,
    pub is_current: bool,
    pub last_active: f64,
    pub added_at: f64,
    pub is_new: bool,
}

#[derive(Clone, Debug)]
pub struct Chat {
    pub id: String,
    pub chat_type: String, // "direct" | "group"
    pub name: String,
    pub avatar_url: Option<String>,
    pub participant_ids: Vec<String>,
    pub last_message: Option<Message>,
    pub unread_count: u32,
    pub is_pinned: bool,
    pub is_muted: bool,
    pub muted_until: Option<f64>,
    pub is_archived: bool,
    pub has_security_changes: bool,
    pub device_count: Option<u32>,
}

#[derive(Clone, Debug)]
pub struct Message {
    pub id: String,
    pub chat_id: String,
    pub sender_id: String,
    pub sender_name: String,
    pub sender_avatar: Option<String>,
    pub msg_type: String, // "text" | "voice" | "image" | "video" | "file" | "system"
    pub content: String,
    pub timestamp: f64,
    pub status: String, // "sending" | "sent" | "delivered" | "read"
    pub is_own: bool,
    pub is_edited: bool,
    pub is_deleted: bool,
    pub reply_to: Option<Box<ReplyTo>>,
    pub reactions: Vec<Reaction>,
    pub thread_count: Option<u32>,
    // Voice specific
    pub duration: Option<u32>,
    pub waveform: Vec<f64>,
    pub transcription: Option<String>,
    // Media specific
    pub media_url: Option<String>,
    pub thumbnail_url: Option<String>,
    pub file_name: Option<String>,
    pub file_size: Option<u64>,
    // System specific
    pub system_action: Option<String>,
}

#[derive(Clone, Debug)]
pub struct ReplyTo {
    pub id: String,
    pub sender_name: String,
    pub content: String,
}

#[derive(Clone, Debug)]
pub struct Reaction {
    pub emoji: String,
    pub count: u32,
    pub users: Vec<String>,
    pub has_own: bool,
}

#[derive(Clone, Debug)]
pub struct Invitation {
    pub id: String,
    pub token: String,
    pub role: String,
    pub max_uses: u32,
    pub used_count: u32,
    pub expires_at: f64,
    pub created_at: f64,
    pub created_by: Option<String>,
    pub status: String,
}

#[derive(Clone, Debug)]
pub struct ServerStats {
    pub total_users: u32,
    pub active_users_day: u32,
    pub total_groups: u32,
    pub messages_day: u32,
}

#[derive(Clone, Debug)]
pub struct AdminUser {
    pub id: String,
    pub username: String,
    pub display_name: String,
    pub avatar_url: Option<String>,
    pub role: String,
    pub status: String,
    pub created_at: f64,
    pub last_active: f64,
}

// ── Mock data ───────────────────────────────────────────────────────────────

pub fn now_ms() -> f64 {
    js_sys::Date::now()
}

pub fn days_ago(days: f64) -> f64 {
    now_ms() - days * 24.0 * 60.0 * 60.0 * 1000.0
}

pub fn hours_ago(hours: f64) -> f64 {
    now_ms() - hours * 60.0 * 60.0 * 1000.0
}

pub fn minutes_ago(minutes: f64) -> f64 {
    now_ms() - minutes * 60.0 * 1000.0
}

fn gen_waveform(length: u32) -> Vec<f64> {
    // Use a simple deterministic approach (since we can't use rand easily in wasm)
    let mut out = Vec::with_capacity(length as usize);
    let mut seed: f64 = 0.5;
    for _ in 0..length {
        seed = (seed * 1.618 + 0.5) % 1.0;
        out.push(seed * 0.8 + 0.2);
    }
    out
}

pub fn mock_current_user() -> User {
    User {
        id: "user-1".into(),
        username: "ivanov".into(),
        display_name: "Иван Иванов".into(),
        avatar_url: None,
        bio: Some("Product Manager".into()),
        role: "admin".into(),
        created_at: days_ago(120.0),
    }
}

pub fn mock_users() -> Vec<User> {
    vec![
        User {
            id: "user-2".into(),
            username: "petrova".into(),
            display_name: "Анна Петрова".into(),
            avatar_url: None,
            bio: Some("Designer".into()),
            role: "user".into(),
            created_at: days_ago(100.0),
        },
        User {
            id: "user-3".into(),
            username: "sidorov".into(),
            display_name: "Алексей Сидоров".into(),
            avatar_url: None,
            bio: Some("Developer".into()),
            role: "user".into(),
            created_at: days_ago(80.0),
        },
        User {
            id: "user-4".into(),
            username: "kozlova".into(),
            display_name: "Мария Козлова".into(),
            avatar_url: None,
            bio: Some("QA Engineer".into()),
            role: "user".into(),
            created_at: days_ago(60.0),
        },
        User {
            id: "user-5".into(),
            username: "johnsmith".into(),
            display_name: "John Smith".into(),
            avatar_url: None,
            bio: Some("CEO".into()),
            role: "owner".into(),
            created_at: days_ago(140.0),
        },
        User {
            id: "user-6".into(),
            username: "emilydavis".into(),
            display_name: "Emily Davis".into(),
            avatar_url: None,
            bio: Some("Marketing Lead".into()),
            role: "user".into(),
            created_at: days_ago(50.0),
        },
        User {
            id: "user-7".into(),
            username: "michaelchen".into(),
            display_name: "Michael Chen".into(),
            avatar_url: None,
            bio: Some("Backend Developer".into()),
            role: "user".into(),
            created_at: days_ago(45.0),
        },
        User {
            id: "user-8".into(),
            username: "sarahwilson".into(),
            display_name: "Sarah Wilson".into(),
            avatar_url: None,
            bio: Some("HR Manager".into()),
            role: "admin".into(),
            created_at: days_ago(110.0),
        },
    ]
}

pub fn mock_devices() -> Vec<Device> {
    vec![
        Device {
            id: "device-1".into(),
            name: "MacBook Pro".into(),
            device_type: "desktop".into(),
            is_current: true,
            last_active: now_ms(),
            added_at: days_ago(350.0),
            is_new: false,
        },
        Device {
            id: "device-2".into(),
            name: "iPhone 15".into(),
            device_type: "smartphone".into(),
            is_current: false,
            last_active: minutes_ago(30.0),
            added_at: days_ago(340.0),
            is_new: false,
        },
        Device {
            id: "device-3".into(),
            name: "iPad Pro".into(),
            device_type: "tablet".into(),
            is_current: false,
            last_active: days_ago(2.0),
            added_at: days_ago(320.0),
            is_new: true,
        },
        Device {
            id: "device-4".into(),
            name: "Windows Desktop".into(),
            device_type: "desktop".into(),
            is_current: false,
            last_active: days_ago(7.0),
            added_at: days_ago(380.0),
            is_new: false,
        },
    ]
}

fn create_messages_for(chat_id: &str, participant_id: &str, participant_name: &str) -> Vec<Message> {
    let mut msgs = Vec::new();

    let day1 = days_ago(3.0);

    msgs.push(Message {
        id: format!("{chat_id}-msg-1"),
        chat_id: chat_id.into(),
        sender_id: participant_id.into(),
        sender_name: participant_name.into(),
        sender_avatar: None,
        msg_type: "text".into(),
        content: "Привет! Как дела с проектом?".into(),
        timestamp: day1 + 9.0 * 3600.0 * 1000.0,
        status: "read".into(),
        is_own: false,
        is_edited: false,
        is_deleted: false,
        reply_to: None,
        reactions: vec![Reaction {
            emoji: "👍".into(),
            count: 1,
            users: vec!["user-1".into()],
            has_own: true,
        }],
        thread_count: None,
        duration: None,
        waveform: vec![],
        transcription: None,
        media_url: None,
        thumbnail_url: None,
        file_name: None,
        file_size: None,
        system_action: None,
    });

    msgs.push(Message {
        id: format!("{chat_id}-msg-2"),
        chat_id: chat_id.into(),
        sender_id: "user-1".into(),
        sender_name: "Иван Иванов".into(),
        sender_avatar: None,
        msg_type: "text".into(),
        content: "Привет! Все идет по плану, завтра планирую закончить основную часть.".into(),
        timestamp: day1 + 9.0 * 3600.0 * 1000.0 + 5.0 * 60.0 * 1000.0,
        status: "read".into(),
        is_own: true,
        is_edited: false,
        is_deleted: false,
        reply_to: None,
        reactions: vec![],
        thread_count: None,
        duration: None,
        waveform: vec![],
        transcription: None,
        media_url: None,
        thumbnail_url: None,
        file_name: None,
        file_size: None,
        system_action: None,
    });

    msgs.push(Message {
        id: format!("{chat_id}-msg-3"),
        chat_id: chat_id.into(),
        sender_id: participant_id.into(),
        sender_name: participant_name.into(),
        sender_avatar: None,
        msg_type: "text".into(),
        content: "Отлично! Не забудь про документацию 📝".into(),
        timestamp: day1 + 9.0 * 3600.0 * 1000.0 + 10.0 * 60.0 * 1000.0,
        status: "read".into(),
        is_own: false,
        is_edited: false,
        is_deleted: false,
        reply_to: None,
        reactions: vec![],
        thread_count: None,
        duration: None,
        waveform: vec![],
        transcription: None,
        media_url: None,
        thumbnail_url: None,
        file_name: None,
        file_size: None,
        system_action: None,
    });

    // Voice message
    msgs.push(Message {
        id: format!("{chat_id}-msg-4"),
        chat_id: chat_id.into(),
        sender_id: "user-1".into(),
        sender_name: "Иван Иванов".into(),
        sender_avatar: None,
        msg_type: "voice".into(),
        content: String::new(),
        timestamp: hours_ago(14.0),
        status: "read".into(),
        is_own: true,
        is_edited: false,
        is_deleted: false,
        reply_to: None,
        reactions: vec![],
        thread_count: None,
        duration: Some(45),
        waveform: gen_waveform(40),
        transcription: None,
        media_url: None,
        thumbnail_url: None,
        file_name: None,
        file_size: None,
        system_action: None,
    });

    // Reply to voice
    msgs.push(Message {
        id: format!("{chat_id}-msg-5"),
        chat_id: chat_id.into(),
        sender_id: participant_id.into(),
        sender_name: participant_name.into(),
        sender_avatar: None,
        msg_type: "text".into(),
        content: "Понял, спасибо за апдейт!".into(),
        timestamp: hours_ago(13.5),
        status: "read".into(),
        is_own: false,
        is_edited: false,
        is_deleted: false,
        reply_to: Some(Box::new(ReplyTo {
            id: format!("{chat_id}-msg-4"),
            sender_name: "Иван Иванов".into(),
            content: "Голосовое сообщение".into(),
        })),
        reactions: vec![Reaction {
            emoji: "❤️".into(),
            count: 1,
            users: vec!["user-1".into()],
            has_own: true,
        }],
        thread_count: None,
        duration: None,
        waveform: vec![],
        transcription: None,
        media_url: None,
        thumbnail_url: None,
        file_name: None,
        file_size: None,
        system_action: None,
    });

    // Image
    msgs.push(Message {
        id: format!("{chat_id}-msg-6"),
        chat_id: chat_id.into(),
        sender_id: participant_id.into(),
        sender_name: participant_name.into(),
        sender_avatar: None,
        msg_type: "image".into(),
        content: String::new(),
        timestamp: hours_ago(10.0),
        status: "read".into(),
        is_own: false,
        is_edited: false,
        is_deleted: false,
        reply_to: None,
        reactions: vec![
            Reaction {
                emoji: "😍".into(),
                count: 2,
                users: vec!["user-1".into(), "user-3".into()],
                has_own: true,
            },
        ],
        thread_count: None,
        duration: None,
        waveform: vec![],
        transcription: None,
        media_url: None,
        thumbnail_url: None,
        file_name: None,
        file_size: None,
        system_action: None,
    });

    // Text with thread
    msgs.push(Message {
        id: format!("{chat_id}-msg-7"),
        chat_id: chat_id.into(),
        sender_id: "user-1".into(),
        sender_name: "Иван Иванов".into(),
        sender_avatar: None,
        msg_type: "text".into(),
        content: "Выглядит отлично! Можешь скинуть исходники?".into(),
        timestamp: hours_ago(9.5),
        status: "read".into(),
        is_own: true,
        is_edited: true,
        is_deleted: false,
        reply_to: None,
        reactions: vec![],
        thread_count: Some(3),
        duration: None,
        waveform: vec![],
        transcription: None,
        media_url: None,
        thumbnail_url: None,
        file_name: None,
        file_size: None,
        system_action: None,
    });

    // File
    msgs.push(Message {
        id: format!("{chat_id}-msg-8"),
        chat_id: chat_id.into(),
        sender_id: participant_id.into(),
        sender_name: participant_name.into(),
        sender_avatar: None,
        msg_type: "file".into(),
        content: String::new(),
        timestamp: hours_ago(9.0),
        status: "read".into(),
        is_own: false,
        is_edited: false,
        is_deleted: false,
        reply_to: None,
        reactions: vec![],
        thread_count: None,
        duration: None,
        waveform: vec![],
        transcription: None,
        media_url: None,
        thumbnail_url: None,
        file_name: Some("design_v2.fig".into()),
        file_size: Some(2_456_789),
        system_action: None,
    });

    // System message
    msgs.push(Message {
        id: format!("{chat_id}-msg-9"),
        chat_id: chat_id.into(),
        sender_id: "system".into(),
        sender_name: "System".into(),
        sender_avatar: None,
        msg_type: "system".into(),
        content: format!("У {participant_name} появилось новое устройство — сверьте safety number"),
        timestamp: hours_ago(2.0),
        status: "read".into(),
        is_own: false,
        is_edited: false,
        is_deleted: false,
        reply_to: None,
        reactions: vec![],
        thread_count: None,
        duration: None,
        waveform: vec![],
        transcription: None,
        media_url: None,
        thumbnail_url: None,
        file_name: None,
        file_size: None,
        system_action: Some("new_device".into()),
    });

    // Voice with transcription
    msgs.push(Message {
        id: format!("{chat_id}-msg-10"),
        chat_id: chat_id.into(),
        sender_id: participant_id.into(),
        sender_name: participant_name.into(),
        sender_avatar: None,
        msg_type: "voice".into(),
        content: String::new(),
        timestamp: hours_ago(1.0),
        status: "read".into(),
        is_own: false,
        is_edited: false,
        is_deleted: false,
        reply_to: None,
        reactions: vec![],
        thread_count: None,
        duration: Some(127),
        waveform: gen_waveform(50),
        transcription: Some("Привет, хотел обсудить план на следующую неделю. У нас есть несколько важных задач которые нужно закончить...".into()),
        media_url: None,
        thumbnail_url: None,
        file_name: None,
        file_size: None,
        system_action: None,
    });

    // Recent messages
    msgs.push(Message {
        id: format!("{chat_id}-msg-11"),
        chat_id: chat_id.into(),
        sender_id: "user-1".into(),
        sender_name: "Иван Иванов".into(),
        sender_avatar: None,
        msg_type: "text".into(),
        content: "Хорошо, давай созвонимся после обеда. У меня будет время в 15:00.".into(),
        timestamp: minutes_ago(30.0),
        status: "delivered".into(),
        is_own: true,
        is_edited: false,
        is_deleted: false,
        reply_to: None,
        reactions: vec![],
        thread_count: None,
        duration: None,
        waveform: vec![],
        transcription: None,
        media_url: None,
        thumbnail_url: None,
        file_name: None,
        file_size: None,
        system_action: None,
    });

    msgs.push(Message {
        id: format!("{chat_id}-msg-12"),
        chat_id: chat_id.into(),
        sender_id: participant_id.into(),
        sender_name: participant_name.into(),
        sender_avatar: None,
        msg_type: "text".into(),
        content: "Договорились! 👌".into(),
        timestamp: minutes_ago(25.0),
        status: "read".into(),
        is_own: false,
        is_edited: false,
        is_deleted: false,
        reply_to: None,
        reactions: vec![Reaction {
            emoji: "👍".into(),
            count: 1,
            users: vec!["user-1".into()],
            has_own: true,
        }],
        thread_count: None,
        duration: None,
        waveform: vec![],
        transcription: None,
        media_url: None,
        thumbnail_url: None,
        file_name: None,
        file_size: None,
        system_action: None,
    });

    msgs
}

fn create_group_messages() -> Vec<Message> {
    let chat_id = "chat-group-1";
    let mut msgs = Vec::new();

    msgs.push(Message {
        id: format!("{chat_id}-msg-1"),
        chat_id: chat_id.into(),
        sender_id: "system".into(),
        sender_name: "System".into(),
        sender_avatar: None,
        msg_type: "system".into(),
        content: "John Smith создал группу \"Project Alpha Team\"".into(),
        timestamp: days_ago(7.0),
        status: "read".into(),
        is_own: false,
        is_edited: false,
        is_deleted: false,
        reply_to: None,
        reactions: vec![],
        thread_count: None,
        duration: None,
        waveform: vec![],
        transcription: None,
        media_url: None,
        thumbnail_url: None,
        file_name: None,
        file_size: None,
        system_action: None,
    });

    msgs.push(Message {
        id: format!("{chat_id}-msg-2"),
        chat_id: chat_id.into(),
        sender_id: "system".into(),
        sender_name: "System".into(),
        sender_avatar: None,
        msg_type: "system".into(),
        content: "John Smith добавил(а) Анна Петрова, Алексей Сидоров, Иван Иванов".into(),
        timestamp: days_ago(7.0) + 60_000.0,
        status: "read".into(),
        is_own: false,
        is_edited: false,
        is_deleted: false,
        reply_to: None,
        reactions: vec![],
        thread_count: None,
        duration: None,
        waveform: vec![],
        transcription: None,
        media_url: None,
        thumbnail_url: None,
        file_name: None,
        file_size: None,
        system_action: None,
    });

    msgs.push(Message {
        id: format!("{chat_id}-msg-3"),
        chat_id: chat_id.into(),
        sender_id: "user-5".into(),
        sender_name: "John Smith".into(),
        sender_avatar: None,
        msg_type: "text".into(),
        content: "Welcome everyone! This is our main channel for Project Alpha discussion.".into(),
        timestamp: days_ago(7.0) + 120_000.0,
        status: "read".into(),
        is_own: false,
        is_edited: false,
        is_deleted: false,
        reply_to: None,
        reactions: vec![Reaction {
            emoji: "👋".into(),
            count: 3,
            users: vec!["user-1".into(), "user-2".into(), "user-3".into()],
            has_own: true,
        }],
        thread_count: None,
        duration: None,
        waveform: vec![],
        transcription: None,
        media_url: None,
        thumbnail_url: None,
        file_name: None,
        file_size: None,
        system_action: None,
    });

    // Add more group messages
    msgs.push(Message {
        id: format!("{chat_id}-msg-4"),
        chat_id: chat_id.into(),
        sender_id: "user-2".into(),
        sender_name: "Анна Петрова".into(),
        sender_avatar: None,
        msg_type: "text".into(),
        content: "Привет всем! Рада быть в команде 😊".into(),
        timestamp: days_ago(6.0),
        status: "read".into(),
        is_own: false,
        is_edited: false,
        is_deleted: false,
        reply_to: None,
        reactions: vec![Reaction {
            emoji: "❤️".into(),
            count: 2,
            users: vec!["user-1".into(), "user-5".into()],
            has_own: true,
        }],
        thread_count: None,
        duration: None,
        waveform: vec![],
        transcription: None,
        media_url: None,
        thumbnail_url: None,
        file_name: None,
        file_size: None,
        system_action: None,
    });

    msgs.push(Message {
        id: format!("{chat_id}-msg-5"),
        chat_id: chat_id.into(),
        sender_id: "user-1".into(),
        sender_name: "Иван Иванов".into(),
        sender_avatar: None,
        msg_type: "text".into(),
        content: "Всем привет! Когда планируем первый созвон?".into(),
        timestamp: days_ago(5.0),
        status: "read".into(),
        is_own: true,
        is_edited: false,
        is_deleted: false,
        reply_to: None,
        reactions: vec![],
        thread_count: Some(5),
        duration: None,
        waveform: vec![],
        transcription: None,
        media_url: None,
        thumbnail_url: None,
        file_name: None,
        file_size: None,
        system_action: None,
    });

    msgs.push(Message {
        id: format!("{chat_id}-msg-6"),
        chat_id: chat_id.into(),
        sender_id: "user-3".into(),
        sender_name: "Алексей Сидоров".into(),
        sender_avatar: None,
        msg_type: "file".into(),
        content: String::new(),
        timestamp: days_ago(4.0),
        status: "read".into(),
        is_own: false,
        is_edited: false,
        is_deleted: false,
        reply_to: None,
        reactions: vec![],
        thread_count: None,
        duration: None,
        waveform: vec![],
        transcription: None,
        media_url: None,
        thumbnail_url: None,
        file_name: Some("project_requirements.pdf".into()),
        file_size: Some(1_234_567),
        system_action: None,
    });

    msgs.push(Message {
        id: format!("{chat_id}-msg-7"),
        chat_id: chat_id.into(),
        sender_id: "user-5".into(),
        sender_name: "John Smith".into(),
        sender_avatar: None,
        msg_type: "text".into(),
        content: "Great work on the requirements doc! Let's review it tomorrow at 10 AM.".into(),
        timestamp: days_ago(3.0),
        status: "read".into(),
        is_own: false,
        is_edited: false,
        is_deleted: false,
        reply_to: None,
        reactions: vec![Reaction {
            emoji: "👍".into(),
            count: 4,
            users: vec!["user-1".into(), "user-2".into(), "user-3".into(), "user-4".into()],
            has_own: true,
        }],
        thread_count: None,
        duration: None,
        waveform: vec![],
        transcription: None,
        media_url: None,
        thumbnail_url: None,
        file_name: None,
        file_size: None,
        system_action: None,
    });

    msgs
}

pub fn mock_chats() -> Vec<Chat> {
    let users = mock_users();
    vec![
        Chat {
            id: "chat-1".into(),
            chat_type: "direct".into(),
            name: "Анна Петрова".into(),
            avatar_url: None,
            participant_ids: vec!["user-2".into()],
            last_message: Some(Message {
                id: "last-1".into(),
                chat_id: "chat-1".into(),
                sender_id: "user-2".into(),
                sender_name: "Анна Петрова".into(),
                sender_avatar: None,
                msg_type: "text".into(),
                content: "Договорились! 👌".into(),
                timestamp: minutes_ago(25.0),
                status: "read".into(),
                is_own: false,
                is_edited: false,
                is_deleted: false,
                reply_to: None,
                reactions: vec![],
                thread_count: None,
                duration: None,
                waveform: vec![],
                transcription: None,
                media_url: None,
                thumbnail_url: None,
                file_name: None,
                file_size: None,
                system_action: None,
            }),
            unread_count: 0,
            is_pinned: true,
            is_muted: false,
            muted_until: None,
            is_archived: false,
            has_security_changes: true,
            device_count: Some(3),
        },
        Chat {
            id: "chat-group-1".into(),
            chat_type: "group".into(),
            name: "Project Alpha Team".into(),
            avatar_url: None,
            participant_ids: vec!["user-2".into(), "user-3".into(), "user-5".into()],
            last_message: Some(Message {
                id: "last-group-1".into(),
                chat_id: "chat-group-1".into(),
                sender_id: "user-1".into(),
                sender_name: "Иван Иванов".into(),
                sender_avatar: None,
                msg_type: "text".into(),
                content: "Сделаю! 💪".into(),
                timestamp: hours_ago(1.0),
                status: "delivered".into(),
                is_own: true,
                is_edited: false,
                is_deleted: false,
                reply_to: None,
                reactions: vec![],
                thread_count: None,
                duration: None,
                waveform: vec![],
                transcription: None,
                media_url: None,
                thumbnail_url: None,
                file_name: None,
                file_size: None,
                system_action: None,
            }),
            unread_count: 3,
            is_pinned: true,
            is_muted: false,
            muted_until: None,
            is_archived: false,
            has_security_changes: false,
            device_count: None,
        },
        Chat {
            id: "chat-2".into(),
            chat_type: "direct".into(),
            name: "Алексей Сидоров".into(),
            avatar_url: None,
            participant_ids: vec!["user-3".into()],
            last_message: Some(Message {
                id: "last-2".into(),
                chat_id: "chat-2".into(),
                sender_id: "user-1".into(),
                sender_name: "Иван Иванов".into(),
                sender_avatar: None,
                msg_type: "text".into(),
                content: "Спасибо за код ревью!".into(),
                timestamp: hours_ago(3.0),
                status: "read".into(),
                is_own: true,
                is_edited: false,
                is_deleted: false,
                reply_to: None,
                reactions: vec![],
                thread_count: None,
                duration: None,
                waveform: vec![],
                transcription: None,
                media_url: None,
                thumbnail_url: None,
                file_name: None,
                file_size: None,
                system_action: None,
            }),
            unread_count: 0,
            is_pinned: false,
            is_muted: false,
            muted_until: None,
            is_archived: false,
            has_security_changes: false,
            device_count: Some(2),
        },
        Chat {
            id: "chat-3".into(),
            chat_type: "direct".into(),
            name: "John Smith".into(),
            avatar_url: None,
            participant_ids: vec!["user-5".into()],
            last_message: Some(Message {
                id: "last-3".into(),
                chat_id: "chat-3".into(),
                sender_id: "user-5".into(),
                sender_name: "John Smith".into(),
                sender_avatar: None,
                msg_type: "text".into(),
                content: "Let's sync tomorrow about Q3 plans".into(),
                timestamp: hours_ago(5.0),
                status: "read".into(),
                is_own: false,
                is_edited: false,
                is_deleted: false,
                reply_to: None,
                reactions: vec![],
                thread_count: None,
                duration: None,
                waveform: vec![],
                transcription: None,
                media_url: None,
                thumbnail_url: None,
                file_name: None,
                file_size: None,
                system_action: None,
            }),
            unread_count: 1,
            is_pinned: false,
            is_muted: false,
            muted_until: None,
            is_archived: false,
            has_security_changes: false,
            device_count: Some(4),
        },
        Chat {
            id: "chat-4".into(),
            chat_type: "direct".into(),
            name: "Мария Козлова".into(),
            avatar_url: None,
            participant_ids: vec!["user-4".into()],
            last_message: Some(Message {
                id: "last-4".into(),
                chat_id: "chat-4".into(),
                sender_id: "user-4".into(),
                sender_name: "Мария Козлова".into(),
                sender_avatar: None,
                msg_type: "voice".into(),
                content: String::new(),
                timestamp: hours_ago(8.0),
                status: "read".into(),
                is_own: false,
                is_edited: false,
                is_deleted: false,
                reply_to: None,
                reactions: vec![],
                thread_count: None,
                duration: Some(32),
                waveform: vec![],
                transcription: None,
                media_url: None,
                thumbnail_url: None,
                file_name: None,
                file_size: None,
                system_action: None,
            }),
            unread_count: 0,
            is_pinned: false,
            is_muted: true,
            muted_until: Some(now_ms() + 24.0 * 3600.0 * 1000.0),
            is_archived: false,
            has_security_changes: false,
            device_count: Some(1),
        },
        Chat {
            id: "chat-5".into(),
            chat_type: "direct".into(),
            name: "Emily Davis".into(),
            avatar_url: None,
            participant_ids: vec!["user-6".into()],
            last_message: Some(Message {
                id: "last-5".into(),
                chat_id: "chat-5".into(),
                sender_id: "user-6".into(),
                sender_name: "Emily Davis".into(),
                sender_avatar: None,
                msg_type: "file".into(),
                content: String::new(),
                timestamp: days_ago(1.0),
                status: "read".into(),
                is_own: false,
                is_edited: false,
                is_deleted: false,
                reply_to: None,
                reactions: vec![],
                thread_count: None,
                duration: None,
                waveform: vec![],
                transcription: None,
                media_url: None,
                thumbnail_url: None,
                file_name: Some("Marketing_Plan_Q3.pdf".into()),
                file_size: Some(3_456_789),
                system_action: None,
            }),
            unread_count: 0,
            is_pinned: false,
            is_muted: false,
            muted_until: None,
            is_archived: false,
            has_security_changes: false,
            device_count: Some(2),
        },
        Chat {
            id: "chat-group-2".into(),
            chat_type: "group".into(),
            name: "Design Team".into(),
            avatar_url: None,
            participant_ids: vec!["user-2".into(), "user-6".into()],
            last_message: Some(Message {
                id: "last-group-2".into(),
                chat_id: "chat-group-2".into(),
                sender_id: "user-2".into(),
                sender_name: "Анна Петрова".into(),
                sender_avatar: None,
                msg_type: "image".into(),
                content: String::new(),
                timestamp: days_ago(2.0),
                status: "read".into(),
                is_own: false,
                is_edited: false,
                is_deleted: false,
                reply_to: None,
                reactions: vec![],
                thread_count: None,
                duration: None,
                waveform: vec![],
                transcription: None,
                media_url: None,
                thumbnail_url: None,
                file_name: None,
                file_size: None,
                system_action: None,
            }),
            unread_count: 5,
            is_pinned: false,
            is_muted: false,
            muted_until: None,
            is_archived: false,
            has_security_changes: false,
            device_count: None,
        },
        Chat {
            id: "chat-6".into(),
            chat_type: "direct".into(),
            name: "Michael Chen".into(),
            avatar_url: None,
            participant_ids: vec!["user-7".into()],
            last_message: Some(Message {
                id: "last-6".into(),
                chat_id: "chat-6".into(),
                sender_id: "user-7".into(),
                sender_name: "Michael Chen".into(),
                sender_avatar: None,
                msg_type: "text".into(),
                content: "The API is ready for testing".into(),
                timestamp: days_ago(3.0),
                status: "read".into(),
                is_own: false,
                is_edited: false,
                is_deleted: false,
                reply_to: None,
                reactions: vec![],
                thread_count: None,
                duration: None,
                waveform: vec![],
                transcription: None,
                media_url: None,
                thumbnail_url: None,
                file_name: None,
                file_size: None,
                system_action: None,
            }),
            unread_count: 0,
            is_pinned: false,
            is_muted: false,
            muted_until: None,
            is_archived: false,
            has_security_changes: false,
            device_count: Some(3),
        },
        Chat {
            id: "chat-7".into(),
            chat_type: "direct".into(),
            name: "Sarah Wilson".into(),
            avatar_url: None,
            participant_ids: vec!["user-8".into()],
            last_message: Some(Message {
                id: "last-7".into(),
                chat_id: "chat-7".into(),
                sender_id: "user-8".into(),
                sender_name: "Sarah Wilson".into(),
                sender_avatar: None,
                msg_type: "text".into(),
                content: "Please fill out the survey by Friday".into(),
                timestamp: days_ago(4.0),
                status: "read".into(),
                is_own: false,
                is_edited: false,
                is_deleted: false,
                reply_to: None,
                reactions: vec![],
                thread_count: None,
                duration: None,
                waveform: vec![],
                transcription: None,
                media_url: None,
                thumbnail_url: None,
                file_name: None,
                file_size: None,
                system_action: None,
            }),
            unread_count: 0,
            is_pinned: false,
            is_muted: false,
            muted_until: None,
            is_archived: false,
            has_security_changes: false,
            device_count: Some(2),
        },
        Chat {
            id: "chat-group-3".into(),
            chat_type: "group".into(),
            name: "Backend Guild".into(),
            avatar_url: None,
            participant_ids: vec!["user-7".into(), "user-3".into()],
            last_message: Some(Message {
                id: "last-group-3".into(),
                chat_id: "chat-group-3".into(),
                sender_id: "user-3".into(),
                sender_name: "Алексей Сидоров".into(),
                sender_avatar: None,
                msg_type: "text".into(),
                content: "Кто хочет посмотреть новый RFC?".into(),
                timestamp: days_ago(5.0),
                status: "read".into(),
                is_own: false,
                is_edited: false,
                is_deleted: false,
                reply_to: None,
                reactions: vec![],
                thread_count: None,
                duration: None,
                waveform: vec![],
                transcription: None,
                media_url: None,
                thumbnail_url: None,
                file_name: None,
                file_size: None,
                system_action: None,
            }),
            unread_count: 0,
            is_pinned: false,
            is_muted: false,
            muted_until: None,
            is_archived: false,
            has_security_changes: false,
            device_count: None,
        },
    ]
}

// Messages cache
thread_local! {
    static MESSAGES_CACHE: RefCell<std::collections::HashMap<String, Vec<Message>>> = RefCell::new(std::collections::HashMap::new());
}

pub fn mock_messages(chat_id: &str) -> Vec<Message> {
    MESSAGES_CACHE.with(|cache| {
        let mut cache = cache.borrow_mut();
        if let Some(msgs) = cache.get(chat_id) {
            return msgs.clone();
        }
        let msgs = match chat_id {
            "chat-1" => create_messages_for("chat-1", "user-2", "Анна Петрова"),
            "chat-group-1" => create_group_messages(),
            "chat-2" => create_messages_for("chat-2", "user-3", "Алексей Сидоров"),
            "chat-3" => create_messages_for("chat-3", "user-5", "John Smith"),
            _ => Vec::new(),
        };
        cache.insert(chat_id.to_string(), msgs.clone());
        msgs
    })
}

pub fn mock_thread_messages() -> Vec<Message> {
    vec![
        Message {
            id: "thread-1".into(),
            chat_id: "chat-group-1".into(),
            sender_id: "user-3".into(),
            sender_name: "Алексей Сидоров".into(),
            sender_avatar: None,
            msg_type: "text".into(),
            content: "Давайте в среду в 14:00?".into(),
            timestamp: days_ago(4.0) + 60_000.0,
            status: "read".into(),
            is_own: false,
            is_edited: false,
            is_deleted: false,
            reply_to: None,
            reactions: vec![],
            thread_count: None,
            duration: None,
            waveform: vec![],
            transcription: None,
            media_url: None,
            thumbnail_url: None,
            file_name: None,
            file_size: None,
            system_action: None,
        },
        Message {
            id: "thread-2".into(),
            chat_id: "chat-group-1".into(),
            sender_id: "user-2".into(),
            sender_name: "Анна Петрова".into(),
            sender_avatar: None,
            msg_type: "text".into(),
            content: "Мне подходит!".into(),
            timestamp: days_ago(4.0) + 120_000.0,
            status: "read".into(),
            is_own: false,
            is_edited: false,
            is_deleted: false,
            reply_to: None,
            reactions: vec![],
            thread_count: None,
            duration: None,
            waveform: vec![],
            transcription: None,
            media_url: None,
            thumbnail_url: None,
            file_name: None,
            file_size: None,
            system_action: None,
        },
        Message {
            id: "thread-3".into(),
            chat_id: "chat-group-1".into(),
            sender_id: "user-5".into(),
            sender_name: "John Smith".into(),
            sender_avatar: None,
            msg_type: "text".into(),
            content: "Wednesday 2 PM works for me too. Let's do it!".into(),
            timestamp: days_ago(4.0) + 180_000.0,
            status: "read".into(),
            is_own: false,
            is_edited: false,
            is_deleted: false,
            reply_to: None,
            reactions: vec![Reaction {
                emoji: "👍".into(),
                count: 2,
                users: vec!["user-1".into(), "user-2".into()],
                has_own: true,
            }],
            thread_count: None,
            duration: None,
            waveform: vec![],
            transcription: None,
            media_url: None,
            thumbnail_url: None,
            file_name: None,
            file_size: None,
            system_action: None,
        },
        Message {
            id: "thread-4".into(),
            chat_id: "chat-group-1".into(),
            sender_id: "user-1".into(),
            sender_name: "Иван Иванов".into(),
            sender_avatar: None,
            msg_type: "text".into(),
            content: "Отлично, записал в календарь!".into(),
            timestamp: days_ago(4.0) + 240_000.0,
            status: "read".into(),
            is_own: true,
            is_edited: false,
            is_deleted: false,
            reply_to: None,
            reactions: vec![],
            thread_count: None,
            duration: None,
            waveform: vec![],
            transcription: None,
            media_url: None,
            thumbnail_url: None,
            file_name: None,
            file_size: None,
            system_action: None,
        },
        Message {
            id: "thread-5".into(),
            chat_id: "chat-group-1".into(),
            sender_id: "user-2".into(),
            sender_name: "Анна Петрова".into(),
            sender_avatar: None,
            msg_type: "text".into(),
            content: "Не забудьте подготовить вопросы!".into(),
            timestamp: days_ago(3.0),
            status: "read".into(),
            is_own: false,
            is_edited: false,
            is_deleted: false,
            reply_to: None,
            reactions: vec![],
            thread_count: None,
            duration: None,
            waveform: vec![],
            transcription: None,
            media_url: None,
            thumbnail_url: None,
            file_name: None,
            file_size: None,
            system_action: None,
        },
    ]
}

pub fn mock_invitations() -> Vec<Invitation> {
    vec![
        Invitation {
            id: "inv-1".into(),
            token: "ABCD-EFGH-IJKL-MNOP".into(),
            role: "user".into(),
            max_uses: 5,
            used_count: 2,
            expires_at: now_ms() + 3.0 * 24.0 * 3600.0 * 1000.0,
            created_at: days_ago(4.0),
            created_by: Some("user-1".into()),
            status: "active".into(),
        },
        Invitation {
            id: "inv-2".into(),
            token: "QRST-UVWX-YZAB-CDEF".into(),
            role: "admin".into(),
            max_uses: 1,
            used_count: 0,
            expires_at: now_ms() + 7.0 * 24.0 * 3600.0 * 1000.0,
            created_at: days_ago(1.0),
            created_by: Some("user-1".into()),
            status: "active".into(),
        },
        Invitation {
            id: "inv-3".into(),
            token: "GHIJ-KLMN-OPQR-STUV".into(),
            role: "user".into(),
            max_uses: 10,
            used_count: 10,
            expires_at: now_ms() + 14.0 * 24.0 * 3600.0 * 1000.0,
            created_at: days_ago(10.0),
            created_by: Some("user-5".into()),
            status: "active".into(),
        },
        Invitation {
            id: "inv-4".into(),
            token: "WXYZ-1234-5678-ABCD".into(),
            role: "user".into(),
            max_uses: 3,
            used_count: 1,
            expires_at: days_ago(1.0),
            created_at: days_ago(8.0),
            created_by: Some("user-1".into()),
            status: "expired".into(),
        },
        Invitation {
            id: "inv-5".into(),
            token: "EFGH-9012-3456-IJKL".into(),
            role: "user".into(),
            max_uses: 5,
            used_count: 3,
            expires_at: now_ms() + 30.0 * 24.0 * 3600.0 * 1000.0,
            created_at: days_ago(2.0),
            created_by: Some("user-8".into()),
            status: "revoked".into(),
        },
    ]
}

pub fn mock_server_stats() -> ServerStats {
    ServerStats {
        total_users: 127,
        active_users_day: 89,
        total_groups: 23,
        messages_day: 1456,
    }
}

pub fn mock_admin_users() -> Vec<AdminUser> {
    vec![
        AdminUser {
            id: "user-5".into(),
            username: "johnsmith".into(),
            display_name: "John Smith".into(),
            avatar_url: None,
            role: "owner".into(),
            status: "active".into(),
            created_at: days_ago(140.0),
            last_active: now_ms(),
        },
        AdminUser {
            id: "user-1".into(),
            username: "ivanov".into(),
            display_name: "Иван Иванов".into(),
            avatar_url: None,
            role: "admin".into(),
            status: "active".into(),
            created_at: days_ago(120.0),
            last_active: now_ms(),
        },
        AdminUser {
            id: "user-8".into(),
            username: "sarahwilson".into(),
            display_name: "Sarah Wilson".into(),
            avatar_url: None,
            role: "admin".into(),
            status: "active".into(),
            created_at: days_ago(110.0),
            last_active: hours_ago(2.0),
        },
        AdminUser {
            id: "user-2".into(),
            username: "petrova".into(),
            display_name: "Анна Петрова".into(),
            avatar_url: None,
            role: "user".into(),
            status: "active".into(),
            created_at: days_ago(100.0),
            last_active: minutes_ago(30.0),
        },
        AdminUser {
            id: "user-3".into(),
            username: "sidorov".into(),
            display_name: "Алексей Сидоров".into(),
            avatar_url: None,
            role: "user".into(),
            status: "suspended".into(),
            created_at: days_ago(80.0),
            last_active: days_ago(5.0),
        },
        AdminUser {
            id: "user-4".into(),
            username: "kozlova".into(),
            display_name: "Мария Козлова".into(),
            avatar_url: None,
            role: "user".into(),
            status: "active".into(),
            created_at: days_ago(60.0),
            last_active: hours_ago(6.0),
        },
        AdminUser {
            id: "user-6".into(),
            username: "emilydavis".into(),
            display_name: "Emily Davis".into(),
            avatar_url: None,
            role: "user".into(),
            status: "active".into(),
            created_at: days_ago(50.0),
            last_active: hours_ago(1.0),
        },
        AdminUser {
            id: "user-7".into(),
            username: "michaelchen".into(),
            display_name: "Michael Chen".into(),
            avatar_url: None,
            role: "user".into(),
            status: "active".into(),
            created_at: days_ago(45.0),
            last_active: hours_ago(12.0),
        },
    ]
}

pub const MOCK_SAFETY_NUMBER: &str = "123456 789012 345678 901234 567890 123456";

pub struct ThreadInfo {
    pub parent_message_id: String,
    pub messages: Vec<Message>,
}

// Pending messages to be added (simulates sending)
thread_local! {
    static PENDING_MESSAGES: std::cell::RefCell<std::collections::HashMap<String, Vec<Message>>> =
        std::cell::RefCell::new(std::collections::HashMap::new());
}

pub fn add_message(chat_id: &str, msg: Message) {
    MESSAGES_CACHE.with(|cache| {
        let mut cache = cache.borrow_mut();
        let msgs = cache.entry(chat_id.to_string()).or_default();
        msgs.push(msg);
    });
}

pub fn mock_server_info() -> (&'static str, &'static str, &'static str) {
    ("Acme Corp", "https://messenger.acmecorp.com", "1.0.0")
}
